export { default as HomePage } from "./pages/home/Home"
export {default as LoginPage} from "./pages/auth//Login"
export {default as SignUpPage} from "./pages/auth/SignUp"
export {default as ProductsPage} from "./pages/product/Products" 
export {default as ProductDetailPage} from "./pages/product/ProductDetail"
export {default as ResetPass} from "./pages/auth/ResetPass"
export {default as ForgotPass} from "./pages/auth/ForgotPass"
export {default as VerifyEmailPage} from "./pages/auth/VerifyEmail"
export {default as ProfilePage} from "./pages/profile/Profile"
export {default as Cartpage} from "./pages/product/CartPage"
export {default as CheckOutPage} from "./pages/product/CheckOut"
export {default as RegisterSellerPage} from "./pages/auth/ResigterSeller"
export {default as ShopProfilePage} from "./pages/profile/ShopProfile"
export {default as ShopPage} from "./pages/seller/ShopPage"
export {default as HomePageAdmin} from "./pages/admin/HomePage"