export {default as HomePage } from "./pages/Home"
export {default as AuthPage} from "@pages/auth"
export {default as LoginPage} from "./pages/auth/Login/Login"
// export {default as SignUpPage} from "./pages/auth/SignUp/SignUp"
export {default as ProductsPage} from "./pages/Product" 
export {default as ProductDetailPage} from "./pages/ProductDetail"
// export {default as ResetPass} from "./pages/auth/ResetPass/ResetPass"
// export {default as ForgotPass} from "./pages/auth/ForgotPass/ForgotPass"
// export {default as VerifyEmailPage} from "./pages/auth/VerifyEmail/VerifyEmail"
export {default as ProfilePage} from "./pages/Profile/Profile"
export {default as Cartpage} from "./pages/Cart"
export {default as CheckOutPage} from "./pages/Checkout"
export {default as AddressPage} from "./pages/Addresses"
export {default as AdminPage} from "./pages/admin"
export {default as NotFoundPage} from "./pages/NotFoundPage"
export {default as NewProduct} from "@component/AdminUI/NewProduct"
export {default as OrderPage} from "@pages/Order/index"
export {default as OrderDetailUserPage} from "@pages/OrderDetail/index"
export {default as AdminOrderDetailPage} from "@pages/admin/OrderDetail/index"
export {default as StorePage} from "@pages/store"