export { default as HomePage } from "./pages/home/Home"
export {default as LoginPage} from "./pages/auth/Login/Login"
export {default as SignUpPage} from "./pages/auth/SignUp/SignUp"
export {default as ProductsPage} from "./pages/product/Products" 
export {default as ProductDetailPage} from "./pages/product/ProductDetail"
export {default as ResetPass} from "./pages/auth/ResetPass/ResetPass"
export {default as ForgotPass} from "./pages/auth/ForgotPass/ForgotPass"
export {default as VerifyEmailPage} from "./pages/auth/VerifyEmail/VerifyEmail"
export {default as ProfilePage} from "./pages/profile/Profile"
export {default as Cartpage} from "./pages/product/CartPage"
export {default as CheckOutPage} from "./pages/product/CheckOut"
export {default as AddressPage} from "./component/Addresses/Address"
export {default as AdminPage} from "./pages/admin"
export {default as NotFoundPage} from "./pages/NotFoundPage"